export default {
  clearMocks: true,
  collectCoverage: true,
  coverageReporters: ['text'],
  globalSetup: '<rootDir>/tests/setup.ts',
  globalTeardown: '<rootDir>/tests/teardown.ts',
  // globals: {},
  resetMocks: true,
  // setupFiles: [],
  testMatch: ['**/tests/**/?(*.)+(spec|test).ts'],
  verbose: true,
  preset: 'ts-jest',
  testEnvironment: 'node',
  testTimeout: 20000,
  maxWorkers: 1,
  maxConcurrency: 1,
  runner: 'jest-serial-runner',
};
